export default {
    CREATE_TOURNAMENT: 'CREATE_TOURNAMENT',
    CREATE_TOURNAMENT_TABLE: 'CREATE_TOURNAMENT_TABLE',
    START_TOURNAMENT: 'START_TOURNAMENT',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    TOURNAMENT_CREATED: 'TOURNAMENT_CREATED',
    GAME_PLAN_RECEIVED: 'GAME_PLAN_RECEIVED',
    UPDATE_PLAYERS: 'UPDATE_PLAYERS'
}
