export default {
    CREATE_TOURNAMENT: 'CREATE_TOURNAMENT',
    CREATE_TOURNAMENT_TABLE: 'CREATE_TOURNAMENT_TABLE',
    START_TOURNAMENT: 'START_TOURNAMENT',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    TOURNAMENT_CREATED: 'TOURNAMENT_CREATED',
    GAME_PLAN_RECEIVED: 'GAME_PLAN_RECEIVED',
    UPDATE_PLAYERS: 'UPDATE_PLAYERS',
    SET_ACTIVE_GAME: 'SET_ACTIVE_GAME',
    TOURNAMENT_MAP_UPDATE_EVENT: 'TOURNAMENT_MAP_UPDATE_EVENT',
    START_TOURNAMENT_GAME: 'START_TOURNAMENT_GAME',
    TOURNAMENT_ENDED_EVENT: 'TOURNAMENT_ENDED_EVENT',
    KILL_TOURNAMENT: 'KILL_TOURNAMENT',
    SET_CURRENT_TOURNAMENT_FRAME: 'SET_CURRENT_TOURNAMENT_FRAME',
    SET_UPDATE_FREQUENCY_TOURNAMENT: 'SET_UPDATE_FREQUENCY_TOURNAMENT',
    UPDATE_ACTIVE_GAMES_LIST: 'UPDATE_ACTIVE_GAMES_LIST',
    GET_ACTIVE_TOURNAMENT: 'GET_ACTIVE_TOURNAMENT'
}
