export default {
    ADD_GAMES: 'ADD_GAMES',
    START_GAME: 'START_GAME',
    ACTIVE_GAME: 'ACTIVE_GAME',
    MAP_UPDATE_EVENT: 'MAP_UPDATE_EVENT',
    PAUSE_GAME: "PAUSE_GAME",
    RESUME_GAME: "RESUME_GAME",
    SET_UPDATE_FREQUENCY: "SET_UPDATE_FREQUENCY",
    SET_CURRENT_FRAME: "SET_CURRENT_FRAME"
}
